-- ===========================================================================
-- 19 — Stock that reflects reality
--
-- Generated by scripts/generate-stock.py. Do not hand-edit; re-run it.
--
-- Run AFTER schema-16. Safe to re-run.
--
-- WHY
-- Every imported product reads "out of stock" and none of them is. The
-- source says 3393 of 3405 are available; schema-16 wrote that
-- into stock_status, and schema-07's trigger overwrote it on the way in,
-- because it derives the status from stock_quantity and the import had
-- no counts to give it.
--
-- Inventing 3405 counts to satisfy the trigger would be inventing data,
-- and it would drift the first time anything sold. Instead a product now
-- says whether it is counted at all.
-- ===========================================================================

-- Counted in the warehouse, or simply stocked? Existing products keep
-- today's behaviour; the import does not.
alter table public.products
  add column if not exists track_stock boolean not null default true;

comment on column public.products.track_stock is
  'True: stock_status follows stock_quantity. False: stock_status is set directly.';

-- The trigger stops speaking for products nobody counts.
create or replace function public.derive_stock_status()
returns trigger
language plpgsql
as $$
begin
  if not new.track_stock then
    -- Untracked: whoever set the status meant it. Only an unrecognised
    -- value gets a default, so an insert that says nothing is stocked.
    if new.stock_status is null
       or new.stock_status not in ('in-stock', 'low-stock', 'out-of-stock') then
      new.stock_status := 'in-stock';
    end if;
    return new;
  end if;

  new.stock_status := case
    when new.stock_quantity <= 0 then 'out-of-stock'
    when new.stock_quantity <= new.low_stock_threshold then 'low-stock'
    else 'in-stock'
  end;
  return new;
end;
$$;

-- The imported catalogue is not counted.
update public.products
   set track_stock = false,
       stock_status = 'in-stock',
       updated_at = now()
 where id like 'zn-%';

-- Except the ones the source says are genuinely unavailable.
update public.products
   set stock_status = 'out-of-stock',
       updated_at = now()
 where id in (
    'zn-60w-led-light-bulb-daylight-4-a19-bulbs',
    'zn-90ef-l-shower-glass-10mm-clear',
    'zn-90l-shower-glass-6mm-clear-side-glass',
    'zn-ck324-36-36-shower-glass-diamond',
    'zn-ck339-39-39-shower-glass-diamond',
    'zn-q100-39-39-shower-glass-set-round',
    'zn-q122-4-shower-glass-6mm-clear',
    'zn-q1524-5-shower-glass-6mm-clear',
    'zn-q1524a-5-shower-glass-8mm-clear',
    'zn-q1524b-5-shower-glass-8mm-design',
    'zn-q80-32-32-shower-glass-set-round',
    'zn-q90-36-36-shower-glass-set-round'
 );

-- What happened, so the run can be checked rather than assumed.
select
  count(*) filter (where stock_status = 'in-stock') as in_stock,
  count(*) filter (where stock_status = 'low-stock') as low_stock,
  count(*) filter (where stock_status = 'out-of-stock') as out_of_stock,
  count(*) filter (where not track_stock) as untracked
  from public.products
 where is_active;
