-- ===========================================================================
-- 11 — Catalogue for generated package selections
--
-- Safe to re-run, like every migration before it.
--
-- schema-10 generates a checklist of decisions (toilet, vanity, shower
-- valve, backsplash...). Those requirements are useless without products
-- to choose from, and the original seed carried 13 items across 9
-- categories. This adds eight categories and the products the taxonomy in
-- data/packages/selection-items.ts points at, at two or three price points
-- each so Basic / Medium / Luxury allowances all have something to land on.
--
-- Placeholder inventory, like the original seed: invented house-brand
-- products, no photographs, and deliberately rating 0 with no reviews —
-- a seeded review count would make "Top rated" rank on fiction. Replace
-- with real inventory before launch.
-- ===========================================================================

insert into public.product_categories (id, name, slug, icon, sort_order) values
  ('cabinetry', 'Cabinetry & Vanities', 'cabinetry', 'Boxes', 10),
  ('countertops', 'Countertops', 'countertops', 'Ruler', 11),
  ('tile', 'Tile & Stone', 'tile-stone', 'LayoutGrid', 12),
  ('appliances', 'Appliances', 'appliances', 'Package', 13),
  ('hvac', 'Heating & Cooling', 'heating-cooling', 'AlertTriangle', 14),
  ('smart-home', 'Smart Home', 'smart-home', 'ShieldCheck', 15),
  ('outdoor', 'Decking & Outdoor', 'decking-outdoor', 'Building2', 16),
  ('window-coverings', 'Window Coverings', 'window-coverings', 'Home', 17)
on conflict (id) do nothing;

insert into public.products
  (id, name, slug, description, category_id, brand, price, homeowner_price,
   contractor_price, unit, stock_status, stock_quantity, rating, review_count,
   delivery_estimate, image_tone, specifications)
values
  ('plb-toilet-basic', 'Two-Piece Toilet — Standard', 'two-piece-toilet-standard',
   'Two-piece elongated toilet, 4.8 L single flush.', 'plumbing', 'CareBy Select',
   289, 289, 254.32, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-toilet-comfort', 'Comfort-Height Toilet — Dual Flush', 'comfort-height-toilet-dual-flush',
   'Comfort height, dual flush, soft-close seat included.', 'plumbing', 'CareBy Select',
   489, 489, 430.32, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-toilet-premium', 'Wall-Hung Toilet with Concealed Tank', 'wall-hung-toilet-with-concealed-tank',
   'Wall-hung pan with in-wall carrier and concealed cistern.', 'plumbing', 'CareBy Select',
   1290, 1290, 1135.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-sink-basin', 'Undermount Basin', 'undermount-basin',
   'Vitreous china undermount basin for stone tops.', 'plumbing', 'CareBy Select',
   165, 165, 145.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-sink-vessel', 'Vessel Basin — Matte', 'vessel-basin-matte',
   'Above-counter vessel basin, matte finish.', 'plumbing', 'CareBy Select',
   340, 340, 299.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-faucet-bath-basic', 'Bathroom Faucet — Single Lever', 'bathroom-faucet-single-lever',
   'Single-hole lever faucet with drain assembly.', 'plumbing', 'CareBy Select',
   179, 179, 157.52, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-faucet-bath-mid', 'Bathroom Faucet — Widespread', 'bathroom-faucet-widespread',
   'Widespread three-hole faucet, ceramic cartridge.', 'plumbing', 'CareBy Select',
   349, 349, 307.12, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-faucet-bath-lux', 'Bathroom Faucet — Wall Mount', 'bathroom-faucet-wall-mount',
   'Wall-mounted faucet with concealed valve body.', 'plumbing', 'CareBy Select',
   720, 720, 633.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-shower-valve', 'Pressure-Balanced Shower Valve', 'pressure-balanced-shower-valve',
   'Rough-in valve and trim, pressure balanced.', 'plumbing', 'CareBy Select',
   285, 285, 250.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-shower-thermo', 'Thermostatic Shower Valve — 2 Outlet', 'thermostatic-shower-valve-2-outlet',
   'Thermostatic valve with diverter for two outlets.', 'plumbing', 'CareBy Select',
   690, 690, 607.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-showerhead-basic', 'Showerhead — Fixed', 'showerhead-fixed',
   'Fixed showerhead, 1.75 gpm.', 'plumbing', 'CareBy Select',
   95, 95, 83.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-showerhead-hand', 'Showerhead with Hand Shower', 'showerhead-with-hand-shower',
   'Fixed head plus slide bar hand shower.', 'plumbing', 'CareBy Select',
   245, 245, 215.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-showerhead-rain', 'Rain Shower — Ceiling Mount', 'rain-shower-ceiling-mount',
   'Ceiling-mounted rain head, 10 in.', 'plumbing', 'CareBy Select',
   620, 620, 545.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-shower-base-acrylic', 'Acrylic Shower Base', 'acrylic-shower-base',
   'Acrylic base with centre drain.', 'plumbing', 'CareBy Select',
   420, 420, 369.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-shower-base-tileable', 'Tileable Shower Base Kit', 'tileable-shower-base-kit',
   'Sloped tileable tray with waterproofing kit.', 'plumbing', 'CareBy Select',
   780, 780, 686.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-tub-alcove', 'Alcove Bathtub', 'alcove-bathtub',
   'Acrylic alcove tub, 60 in.', 'plumbing', 'CareBy Select',
   690, 690, 607.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-tub-freestanding', 'Freestanding Soaker Tub', 'freestanding-soaker-tub',
   'Freestanding acrylic soaker, 67 in.', 'plumbing', 'CareBy Select',
   1850, 1850, 1628.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-tub-filler', 'Floor-Mount Tub Filler', 'floor-mount-tub-filler',
   'Floor-mounted filler with hand shower.', 'plumbing', 'CareBy Select',
   880, 880, 774.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-ksink-double', 'Kitchen Sink — Double Bowl', 'kitchen-sink-double-bowl',
   'Stainless undermount double bowl, 16 gauge.', 'plumbing', 'CareBy Select',
   540, 540, 475.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-ksink-single', 'Kitchen Sink — Single Bowl Workstation', 'kitchen-sink-single-bowl-workstation',
   'Workstation sink with accessories.', 'plumbing', 'CareBy Select',
   890, 890, 783.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-kfaucet-pulldown', 'Kitchen Faucet — Pull-Down', 'kitchen-faucet-pull-down',
   'Pull-down spray faucet, single lever.', 'plumbing', 'CareBy Select',
   320, 320, 281.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-kfaucet-pro', 'Kitchen Faucet — Professional', 'kitchen-faucet-professional',
   'Spring-neck professional faucet.', 'plumbing', 'CareBy Select',
   690, 690, 607.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-pot-filler', 'Pot Filler — Wall Mount', 'pot-filler-wall-mount',
   'Articulating wall-mounted pot filler.', 'plumbing', 'CareBy Select',
   540, 540, 475.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('plb-laundry-sink', 'Laundry Utility Sink', 'laundry-utility-sink',
   'Moulded utility sink with cabinet base.', 'plumbing', 'CareBy Select',
   310, 310, 272.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-vanity-24', 'Vanity 24 in — Shaker', 'vanity-24-in-shaker',
   '24 in shaker vanity, soft-close doors.', 'cabinetry', 'CareBy Select',
   620, 620, 545.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-vanity-36', 'Vanity 36 in — Slab', 'vanity-36-in-slab',
   '36 in slab-front vanity with drawers.', 'cabinetry', 'CareBy Select',
   1090, 1090, 959.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-vanity-60', 'Vanity 60 in — Double', 'vanity-60-in-double',
   '60 in double vanity, soft-close.', 'cabinetry', 'CareBy Select',
   2290, 2290, 2015.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-kitchen-stock', 'Kitchen Cabinets — Stock Line', 'kitchen-cabinets-stock-line',
   'Stock cabinetry, melamine box, shaker door.', 'cabinetry', 'CareBy Select',
   320, 320, 281.6, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-kitchen-semi', 'Kitchen Cabinets — Semi-Custom', 'kitchen-cabinets-semi-custom',
   'Semi-custom cabinetry, plywood box.', 'cabinetry', 'CareBy Select',
   540, 540, 475.2, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-kitchen-custom', 'Kitchen Cabinets — Custom', 'kitchen-cabinets-custom',
   'Custom cabinetry built to drawing.', 'cabinetry', 'CareBy Select',
   980, 980, 862.4, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-island', 'Kitchen Island Cabinet', 'kitchen-island-cabinet',
   'Island base cabinet with seating overhang support.', 'cabinetry', 'CareBy Select',
   2400, 2400, 2112.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-pantry', 'Pantry Cabinet System', 'pantry-cabinet-system',
   'Tall pantry with pull-out shelving.', 'cabinetry', 'CareBy Select',
   1850, 1850, 1628.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-wetbar', 'Wet Bar Cabinet Run', 'wet-bar-cabinet-run',
   'Bar cabinetry with sink base and upper display.', 'cabinetry', 'CareBy Select',
   3200, 3200, 2816.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-builtin', 'Built-In Shelving Unit', 'built-in-shelving-unit',
   'Built-in shelving, paint-grade.', 'cabinetry', 'CareBy Select',
   1600, 1600, 1408.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-media-wall', 'Media Wall Unit', 'media-wall-unit',
   'Media wall with cable management.', 'cabinetry', 'CareBy Select',
   2600, 2600, 2288.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-laundry', 'Laundry Cabinet Set', 'laundry-cabinet-set',
   'Upper and lower laundry cabinets.', 'cabinetry', 'CareBy Select',
   1450, 1450, 1276.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-shelving', 'Adjustable Shelving Kit', 'adjustable-shelving-kit',
   'Wall-mounted adjustable shelving.', 'cabinetry', 'CareBy Select',
   320, 320, 281.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-desk', 'Built-In Desk', 'built-in-desk',
   'Built-in desk with drawer bank.', 'cabinetry', 'CareBy Select',
   1350, 1350, 1188.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-entry', 'Entry Bench with Cubbies', 'entry-bench-with-cubbies',
   'Bench, hooks and shoe storage.', 'cabinetry', 'CareBy Select',
   1750, 1750, 1540.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-closet', 'Closet Organiser System', 'closet-organiser-system',
   'Adjustable closet system with drawers.', 'cabinetry', 'CareBy Select',
   1450, 1450, 1276.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('cab-millwork', 'Custom Millwork — Allowance', 'custom-millwork-allowance',
   'Custom millwork package, built to drawing.', 'cabinetry', 'CareBy Select',
   4800, 4800, 4224.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ctp-vanity-quartz', 'Vanity Top — Quartz', 'vanity-top-quartz',
   'Quartz vanity top with integrated backsplash.', 'countertops', 'CareBy Select',
   420, 420, 369.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ctp-vanity-stone', 'Vanity Top — Natural Stone', 'vanity-top-natural-stone',
   'Natural stone vanity top, honed.', 'countertops', 'CareBy Select',
   890, 890, 783.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ctp-laminate', 'Countertop — Laminate', 'countertop-laminate',
   'Post-formed laminate countertop.', 'countertops', 'CareBy Select',
   48, 48, 42.24, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ctp-quartz', 'Countertop — Quartz', 'countertop-quartz',
   'Engineered quartz, 3 cm.', 'countertops', 'CareBy Select',
   92, 92, 80.96, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ctp-porcelain', 'Countertop — Porcelain Slab', 'countertop-porcelain-slab',
   'Large-format porcelain slab.', 'countertops', 'CareBy Select',
   145, 145, 127.6, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-ceramic-wall', 'Ceramic Wall Tile 12x24', 'ceramic-wall-tile-12x24',
   'Glazed ceramic wall tile.', 'tile', 'CareBy Select',
   3.2, 3.2, 2.82, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-porcelain-wall', 'Porcelain Wall Tile 12x24', 'porcelain-wall-tile-12x24',
   'Rectified porcelain wall tile.', 'tile', 'CareBy Select',
   5.4, 5.4, 4.75, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-feature', 'Feature Tile — Mosaic', 'feature-tile-mosaic',
   'Mosaic feature tile on mesh.', 'tile', 'CareBy Select',
   18.5, 18.5, 16.28, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-floor-porcelain', 'Porcelain Floor Tile 24x24', 'porcelain-floor-tile-24x24',
   'Rectified porcelain floor tile.', 'tile', 'CareBy Select',
   4.9, 4.9, 4.31, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-floor-stone', 'Natural Stone Floor Tile', 'natural-stone-floor-tile',
   'Honed natural stone floor tile.', 'tile', 'CareBy Select',
   12.8, 12.8, 11.26, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-grout-standard', 'Grout — Sanded', 'grout-sanded',
   'Polymer-modified sanded grout.', 'tile', 'CareBy Select',
   28, 28, 24.64, 'bag', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-grout-epoxy', 'Grout — Epoxy', 'grout-epoxy',
   'Stain-resistant epoxy grout.', 'tile', 'CareBy Select',
   96, 96, 84.48, 'unit', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-backsplash-subway', 'Backsplash Tile — Subway', 'backsplash-tile-subway',
   'Ceramic subway tile.', 'tile', 'CareBy Select',
   3.8, 3.8, 3.34, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-backsplash-slab', 'Backsplash — Slab Match', 'backsplash-slab-match',
   'Slab backsplash cut to match countertop.', 'tile', 'CareBy Select',
   130, 130, 114.4, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-niche', 'Shower Niche — Preformed', 'shower-niche-preformed',
   'Preformed waterproof niche.', 'tile', 'CareBy Select',
   145, 145, 127.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('tile-bench', 'Shower Bench — Preformed', 'shower-bench-preformed',
   'Preformed waterproof bench.', 'tile', 'CareBy Select',
   310, 310, 272.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-vanity-light', 'Vanity Light Bar', 'vanity-light-bar',
   'LED vanity light bar.', 'electrical', 'CareBy Select',
   165, 165, 145.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-vanity-light-lux', 'Vanity Light — Designer', 'vanity-light-designer',
   'Designer vanity fixture.', 'electrical', 'CareBy Select',
   480, 480, 422.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-pendant', 'Pendant Light', 'pendant-light',
   'Kitchen pendant, dimmable LED.', 'electrical', 'CareBy Select',
   210, 210, 184.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-flush-mount', 'Flush Mount Ceiling Light', 'flush-mount-ceiling-light',
   'LED flush mount fixture.', 'electrical', 'CareBy Select',
   95, 95, 83.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-pot-light', 'Recessed Pot Light', 'recessed-pot-light',
   '4 in LED recessed light, dimmable.', 'electrical', 'CareBy Select',
   38, 38, 33.44, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-chandelier', 'Chandelier', 'chandelier',
   'Multi-arm chandelier fixture.', 'electrical', 'CareBy Select',
   980, 980, 862.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-switch', 'Switch & Receptacle Set', 'switch-receptacle-set',
   'Decora switch and receptacle with plate.', 'electrical', 'CareBy Select',
   14, 14, 12.32, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-dimmer', 'Dimmer Switch', 'dimmer-switch',
   'Universal LED dimmer.', 'electrical', 'CareBy Select',
   42, 42, 36.96, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-exhaust-fan', 'Bathroom Exhaust Fan 110 CFM', 'bathroom-exhaust-fan-110-cfm',
   'Quiet exhaust fan, 110 CFM.', 'electrical', 'CareBy Select',
   165, 165, 145.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-exhaust-fan-light', 'Exhaust Fan with Light', 'exhaust-fan-with-light',
   'Fan and LED light combination.', 'electrical', 'CareBy Select',
   280, 280, 246.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-heated-floor', 'Heated Floor Mat System', 'heated-floor-mat-system',
   'Electric heated floor mat with thermostat.', 'electrical', 'CareBy Select',
   640, 640, 563.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-exterior-light', 'Exterior Wall Light', 'exterior-wall-light',
   'Wet-rated exterior wall fixture.', 'electrical', 'CareBy Select',
   120, 120, 105.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('ele-data-point', 'Data Outlet — Cat6', 'data-outlet-cat6',
   'Cat6 data outlet with plate.', 'electrical', 'CareBy Select',
   55, 55, 48.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-mirror-plain', 'Mirror — Frameless', 'mirror-frameless',
   'Frameless polished-edge mirror.', 'hardware', 'CareBy Select',
   140, 140, 123.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-mirror-framed', 'Mirror — Framed', 'mirror-framed',
   'Framed vanity mirror.', 'hardware', 'CareBy Select',
   290, 290, 255.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-mirror-led', 'Mirror — LED Backlit', 'mirror-led-backlit',
   'LED backlit mirror with defogger.', 'hardware', 'CareBy Select',
   620, 620, 545.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-cabinet-pull', 'Cabinet Pull', 'cabinet-pull',
   'Solid cabinet pull, 5 in centres.', 'hardware', 'CareBy Select',
   9.5, 9.5, 8.36, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-cabinet-knob', 'Cabinet Knob', 'cabinet-knob',
   'Solid cabinet knob.', 'hardware', 'CareBy Select',
   6.8, 6.8, 5.98, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-door-lever', 'Interior Door Lever', 'interior-door-lever',
   'Privacy or passage lever set.', 'hardware', 'CareBy Select',
   38, 38, 33.44, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-door-lever-lux', 'Interior Door Lever — Designer', 'interior-door-lever-designer',
   'Solid brass designer lever.', 'hardware', 'CareBy Select',
   110, 110, 96.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-towel-set', 'Towel Bar & Accessory Set', 'towel-bar-accessory-set',
   'Towel bar, ring and paper holder.', 'hardware', 'CareBy Select',
   120, 120, 105.6, 'set', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hwd-accessory-lux', 'Accessory Set — Designer', 'accessory-set-designer',
   'Designer bathroom accessory set.', 'hardware', 'CareBy Select',
   320, 320, 281.6, 'set', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-fridge-standard', 'Refrigerator — French Door', 'refrigerator-french-door',
   '36 in French door refrigerator.', 'appliances', 'CareBy Select',
   2190, 2190, 1927.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-fridge-counter', 'Refrigerator — Counter Depth', 'refrigerator-counter-depth',
   'Counter-depth French door refrigerator.', 'appliances', 'CareBy Select',
   2990, 2990, 2631.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-fridge-integrated', 'Refrigerator — Panel Ready', 'refrigerator-panel-ready',
   'Panel-ready integrated refrigerator.', 'appliances', 'CareBy Select',
   6800, 6800, 5984.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-range-electric', 'Range — Electric', 'range-electric',
   '30 in freestanding electric range.', 'appliances', 'CareBy Select',
   1290, 1290, 1135.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-range-gas', 'Range — Gas Slide-In', 'range-gas-slide-in',
   '30 in slide-in gas range.', 'appliances', 'CareBy Select',
   2490, 2490, 2191.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-range-dual', 'Range — Dual Fuel 36 in', 'range-dual-fuel-36-in',
   '36 in dual fuel professional range.', 'appliances', 'CareBy Select',
   6200, 6200, 5456.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-hood-insert', 'Range Hood — Insert', 'range-hood-insert',
   'Hood insert with baffle filters.', 'appliances', 'CareBy Select',
   620, 620, 545.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-hood-chimney', 'Range Hood — Chimney', 'range-hood-chimney',
   'Wall-mounted chimney hood.', 'appliances', 'CareBy Select',
   1150, 1150, 1012.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-dishwasher', 'Dishwasher — Built-In', 'dishwasher-built-in',
   'Built-in dishwasher, 45 dBA.', 'appliances', 'CareBy Select',
   890, 890, 783.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-dishwasher-panel', 'Dishwasher — Panel Ready', 'dishwasher-panel-ready',
   'Panel-ready dishwasher, 42 dBA.', 'appliances', 'CareBy Select',
   1690, 1690, 1487.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-microwave', 'Microwave — Over-Range', 'microwave-over-range',
   'Over-the-range microwave.', 'appliances', 'CareBy Select',
   520, 520, 457.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-wall-oven', 'Wall Oven — Single', 'wall-oven-single',
   '30 in single wall oven, convection.', 'appliances', 'CareBy Select',
   2890, 2890, 2543.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-beverage-fridge', 'Beverage Fridge — Undercounter', 'beverage-fridge-undercounter',
   '24 in undercounter beverage centre.', 'appliances', 'CareBy Select',
   1290, 1290, 1135.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-washer', 'Washer — Front Load', 'washer-front-load',
   'Front load washer, steam.', 'appliances', 'CareBy Select',
   1150, 1150, 1012.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('app-dryer', 'Dryer — Electric', 'dryer-electric',
   'Electric dryer with steam.', 'appliances', 'CareBy Select',
   1150, 1150, 1012.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-lvp', 'Luxury Vinyl Plank', 'luxury-vinyl-plank',
   'Rigid core LVP with attached underlay.', 'flooring', 'CareBy Select',
   3.9, 3.9, 3.43, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-laminate', 'Laminate Flooring 12mm', 'laminate-flooring-12mm',
   'AC4 laminate, water resistant.', 'flooring', 'CareBy Select',
   2.8, 2.8, 2.46, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-engineered', 'Engineered Hardwood', 'engineered-hardwood',
   'Engineered oak, 6.5 in wide.', 'flooring', 'CareBy Select',
   7.4, 7.4, 6.51, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-hardwood', 'Solid Hardwood', 'solid-hardwood',
   'Solid white oak, site finished.', 'flooring', 'CareBy Select',
   11.2, 11.2, 9.86, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-underlay', 'Underlayment', 'underlayment',
   'Acoustic underlayment with vapour barrier.', 'flooring', 'CareBy Select',
   0.75, 0.75, 0.66, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-transition', 'Transition Strip', 'transition-strip',
   'Colour-matched transition strip.', 'flooring', 'CareBy Select',
   32, 32, 28.16, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('flr-stair-nosing', 'Stair Nosing', 'stair-nosing',
   'Colour-matched stair nosing.', 'flooring', 'CareBy Select',
   68, 68, 59.84, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-interior-eggshell', 'Interior Paint — Eggshell', 'interior-paint-eggshell',
   'Washable interior eggshell.', 'paint', 'CareBy Select',
   62, 62, 54.56, 'gallon', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-interior-premium', 'Interior Paint — Premium Matte', 'interior-paint-premium-matte',
   'Premium scrubbable matte.', 'paint', 'CareBy Select',
   96, 96, 84.48, 'gallon', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-primer', 'Primer — Interior', 'primer-interior',
   'Stain-blocking interior primer.', 'paint', 'CareBy Select',
   48, 48, 42.24, 'gallon', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-drywall-board', 'Drywall Sheet 4x8', 'drywall-sheet-4x8',
   '½ in regular drywall sheet.', 'paint', 'CareBy Select',
   21, 21, 18.48, 'sheet', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-panel-moulding', 'Wall Panel Moulding Kit', 'wall-panel-moulding-kit',
   'Paint-grade panel moulding kit for feature walls.', 'paint', 'CareBy Select',
   280, 280, 246.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('pnt-exterior', 'Exterior Paint', 'exterior-paint',
   '100% acrylic exterior paint.', 'paint', 'CareBy Select',
   84, 84, 73.92, 'gallon', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-door-hollow', 'Interior Door — Hollow Core', 'interior-door-hollow-core',
   'Primed hollow core door slab.', 'doors-windows', 'CareBy Select',
   145, 145, 127.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-door-solid', 'Interior Door — Solid Core', 'interior-door-solid-core',
   'Primed solid core door slab.', 'doors-windows', 'CareBy Select',
   320, 320, 281.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-door-panel', 'Interior Door — 2 Panel Shaker', 'interior-door-2-panel-shaker',
   'Solid shaker-style interior door.', 'doors-windows', 'CareBy Select',
   480, 480, 422.4, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-exterior-door', 'Exterior Door — Fiberglass', 'exterior-door-fiberglass',
   'Insulated fiberglass entry door.', 'doors-windows', 'CareBy Select',
   1290, 1290, 1135.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-exterior-door-lux', 'Exterior Door — Custom', 'exterior-door-custom',
   'Custom entry door with sidelights.', 'doors-windows', 'CareBy Select',
   3400, 3400, 2992.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-window-vinyl', 'Window — Vinyl Casement', 'window-vinyl-casement',
   'Triple-pane vinyl casement window.', 'doors-windows', 'CareBy Select',
   720, 720, 633.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-window-clad', 'Window — Aluminium Clad', 'window-aluminium-clad',
   'Aluminium clad wood window.', 'doors-windows', 'CareBy Select',
   1650, 1650, 1452.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-garage-door', 'Garage Door — Insulated', 'garage-door-insulated',
   'Insulated sectional garage door.', 'doors-windows', 'CareBy Select',
   2100, 2100, 1848.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-shower-glass-semi', 'Shower Glass — Semi-Frameless', 'shower-glass-semi-frameless',
   'Semi-frameless shower enclosure.', 'doors-windows', 'CareBy Select',
   890, 890, 783.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('dw-shower-glass-frameless', 'Shower Glass — Frameless', 'shower-glass-frameless',
   '10 mm frameless glass enclosure.', 'doors-windows', 'CareBy Select',
   1890, 1890, 1663.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('lum-baseboard-mdf', 'Baseboard — MDF 5¼ in', 'baseboard-mdf-5-in',
   'Primed MDF baseboard.', 'lumber', 'CareBy Select',
   3.1, 3.1, 2.73, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('lum-baseboard-pine', 'Baseboard — Solid Pine', 'baseboard-solid-pine',
   'Solid pine baseboard, paint grade.', 'lumber', 'CareBy Select',
   6.4, 6.4, 5.63, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('lum-stair-kit', 'Stair Tread & Riser Set', 'stair-tread-riser-set',
   'Oak treads and risers with railing.', 'lumber', 'CareBy Select',
   3200, 3200, 2816.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-shingle-arch', 'Architectural Shingles', 'architectural-shingles',
   'Laminated architectural shingles.', 'roofing', 'CareBy Select',
   38, 38, 33.44, 'bundle', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-metal', 'Standing Seam Metal Roofing', 'standing-seam-metal-roofing',
   'Standing seam steel roofing.', 'roofing', 'CareBy Select',
   14.5, 14.5, 12.76, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-siding-vinyl', 'Vinyl Siding', 'vinyl-siding',
   'Insulated vinyl siding.', 'roofing', 'CareBy Select',
   4.2, 4.2, 3.7, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-siding-fibre', 'Fibre Cement Siding', 'fibre-cement-siding',
   'Fibre cement lap siding.', 'roofing', 'CareBy Select',
   8.9, 8.9, 7.83, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-gutter', 'Gutter, Soffit & Fascia', 'gutter-soffit-fascia',
   'Aluminium gutter with soffit and fascia.', 'roofing', 'CareBy Select',
   18, 18, 15.84, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('rfg-brick', 'Brick & Stone Veneer', 'brick-stone-veneer',
   'Masonry veneer, installed allowance.', 'roofing', 'CareBy Select',
   22, 22, 19.36, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-deck-pt', 'Pressure Treated Decking', 'pressure-treated-decking',
   '5/4 pressure treated deck board.', 'outdoor', 'CareBy Select',
   3.4, 3.4, 2.99, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-deck-composite', 'Composite Decking', 'composite-decking',
   'Capped composite deck board.', 'outdoor', 'CareBy Select',
   9.6, 9.6, 8.45, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-deck-pvc', 'PVC Decking', 'pvc-decking',
   'Cellular PVC deck board.', 'outdoor', 'CareBy Select',
   13.8, 13.8, 12.14, 'sq ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-railing-alum', 'Deck Railing — Aluminium', 'deck-railing-aluminium',
   'Powder-coated aluminium railing.', 'outdoor', 'CareBy Select',
   62, 62, 54.56, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-railing-glass', 'Deck Railing — Glass Panel', 'deck-railing-glass-panel',
   'Tempered glass panel railing.', 'outdoor', 'CareBy Select',
   148, 148, 130.24, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-deck-stairs', 'Deck Stair Kit', 'deck-stair-kit',
   'Stringers, treads and railing.', 'outdoor', 'CareBy Select',
   640, 640, 563.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-skirting', 'Deck Skirting', 'deck-skirting',
   'Lattice or board skirting.', 'outdoor', 'CareBy Select',
   22, 22, 19.36, 'linear ft', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-privacy', 'Privacy Screen', 'privacy-screen',
   'Slatted privacy screen panel.', 'outdoor', 'CareBy Select',
   720, 720, 633.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-pergola', 'Pergola Kit', 'pergola-kit',
   'Aluminium pergola kit.', 'outdoor', 'CareBy Select',
   3200, 3200, 2816.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('otd-outdoor-kitchen', 'Outdoor Kitchen Module', 'outdoor-kitchen-module',
   'Weatherproof outdoor kitchen cabinet run.', 'outdoor', 'CareBy Select',
   6400, 6400, 5632.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('smt-switch', 'Smart Switch', 'smart-switch',
   'Wi-Fi smart switch, neutral required.', 'smart-home', 'CareBy Select',
   62, 62, 54.56, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('smt-thermostat', 'Smart Thermostat', 'smart-thermostat',
   'Learning smart thermostat.', 'smart-home', 'CareBy Select',
   285, 285, 250.8, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('smt-lock', 'Smart Lock', 'smart-lock',
   'Keypad smart deadbolt.', 'smart-home', 'CareBy Select',
   340, 340, 299.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('smt-camera', 'Smart Camera', 'smart-camera',
   'Wired outdoor camera.', 'smart-home', 'CareBy Select',
   220, 220, 193.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hvc-register', 'HVAC Register', 'hvac-register',
   'Steel floor or wall register.', 'hvac', 'CareBy Select',
   28, 28, 24.64, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hvc-thermostat', 'Programmable Thermostat', 'programmable-thermostat',
   '7-day programmable thermostat.', 'hvac', 'CareBy Select',
   140, 140, 123.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hvc-fireplace-electric', 'Electric Fireplace', 'electric-fireplace',
   'Linear electric fireplace insert.', 'hvac', 'CareBy Select',
   1290, 1290, 1135.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('hvc-fireplace-gas', 'Gas Fireplace Insert', 'gas-fireplace-insert',
   'Direct vent gas fireplace insert.', 'hvac', 'CareBy Select',
   3600, 3600, 3168.0, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('wcv-blind-roller', 'Roller Blind', 'roller-blind',
   'Light-filtering roller blind, cut to size.', 'window-coverings', 'CareBy Select',
   145, 145, 127.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('wcv-blind-wood', 'Wood Blind', 'wood-blind',
   'Basswood horizontal blind.', 'window-coverings', 'CareBy Select',
   240, 240, 211.2, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb),
  ('wcv-shade-motorised', 'Motorised Shade', 'motorised-shade',
   'Battery motorised roller shade.', 'window-coverings', 'CareBy Select',
   620, 620, 545.6, 'each', 'in-stock', 50, 0, 0,
   'Lead time confirmed at order', 'slate', '[]'::jsonb)
on conflict (id) do nothing;
