"""
Attach photographs and real descriptions to the imported catalogue.

    python scripts/attach-images.py

Reads a native Shopify product export from images/ and writes
supabase/schema-18-product-images.sql.

WHY A CSV AND NOT A SCRAPE
--------------------------
The store's public feed (/products.json) carries the same data, but
pulling it means 3,405 products' worth of requests against a live
storefront. The admin export is one file, one click, no traffic, and it
carries more than the feed does. Shopify writes it from:

    Shopify admin -> Products -> Export -> All products,
                     "CSV for Excel, Numbers, or other spreadsheet"

WHAT IT USES
------------
  Handle        the join key. The catalogue import kept every product's
                handle, so this matches without guessing.
  Image Src     the photograph. Shopify writes one row per image, so the
                first row per handle (Image Position 1) is the main one.
  Body (HTML)   the real description, where the product has one. That
                beats the generated sentence, so it wins when present.

Everything else in the export is ignored: prices and stock came from the
first import and should not be silently re-sourced here.

Requires nothing outside the standard library.
"""

import csv
import glob
import html
import io
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(REPO, "images")
OUT = os.path.join(REPO, "supabase", "schema-18-product-images.sql")

# Shopify serves any size from the same URL by suffixing the filename.
# 800px wide is what the product page and the card actually render at;
# the originals are frequently 2000px+ and would be a slow catalogue on
# a phone for no visible gain.
IMAGE_WIDTH = 800

CHUNK = 1200


def find_export() -> str:
    """The newest CSV in images/ that looks like a Shopify export."""
    best, best_mtime = None, -1
    for path in glob.glob(os.path.join(IMAGES_DIR, "*.csv")):
        with io.open(path, encoding="utf-8-sig", errors="replace") as fh:
            header = fh.readline()
        if "Handle" in header and "Image Src" in header:
            mtime = os.path.getmtime(path)
            if mtime > best_mtime:
                best, best_mtime = path, mtime
    return best


def sized(url: str) -> str:
    """cdn/.../file.jpg?v=1 -> cdn/.../file_800x.jpg?v=1"""
    if not url:
        return url
    base, _, query = url.partition("?")
    root, ext = os.path.splitext(base)
    if not ext:
        return url
    return f"{root}_{IMAGE_WIDTH}x{ext}" + (f"?{query}" if query else "")


TAG = re.compile(r"<[^>]+>")
SPACE = re.compile(r"\s+")


def plain_text(body: str) -> str:
    """
    Shopify descriptions are HTML. The product page renders plain text,
    so the markup is stripped rather than stored and escaped later.
    """
    if not body:
        return ""
    text = re.sub(r"<(br|/p|/div|/li)[^>]*>", " ", body, flags=re.I)
    text = TAG.sub("", text)
    text = html.unescape(text)
    return SPACE.sub(" ", text).strip()


def sql(value) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


HEADER = """-- ===========================================================================
-- 18 — Photographs, and the descriptions Shopify already had
--
-- Generated by scripts/attach-images.py from the Shopify product export.
-- Do not hand-edit; re-run the script.
--
-- Run AFTER schema-16. Matches on the handle each product was imported
-- with, so a product the export no longer carries is left alone rather
-- than blanked.
--
-- Descriptions: only replaced where Shopify has a real one. The
-- generated sentence stays on every product that does not, which is why
-- this is a coalesce rather than a straight assignment.
--
-- Safe to re-run.
-- ===========================================================================
"""


def main() -> int:
    export = find_export()
    if not export:
        print("No Shopify CSV export found in images/.", file=sys.stderr)
        print("Export from: Shopify admin -> Products -> Export -> All "
              "products -> CSV for Excel/Numbers, then drop it in images/.",
              file=sys.stderr)
        return 1
    print("reading", os.path.basename(export))

    # handle -> (image, description). First image row per handle wins,
    # which is Shopify's own position 1.
    images, bodies = {}, {}
    with io.open(export, encoding="utf-8-sig", errors="replace", newline="") as fh:
        for row in csv.DictReader(fh):
            handle = (row.get("Handle") or "").strip()
            if not handle:
                continue
            src = (row.get("Image Src") or "").strip()
            if src and handle not in images:
                images[handle] = sized(src)
            body = plain_text(row.get("Body (HTML)") or "")
            if body and handle not in bodies:
                bodies[handle] = body

    print(f"  {len(images)} handles with an image, {len(bodies)} with a description")

    # The catalogue import is the source of which handle became which id.
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "build_catalogue", os.path.join(REPO, "scripts", "build-catalogue.py"))
    build = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build)

    buf = io.StringIO()
    stdout, sys.stdout = sys.stdout, buf
    try:
        products = build.main()
    finally:
        sys.stdout = stdout

    rows, matched, described = [], 0, 0
    for p in products:
        handle = p["handle"]
        image = images.get(handle)
        body = bodies.get(handle)
        if not image and not body:
            continue
        matched += 1 if image else 0
        described += 1 if body else 0
        rows.append((p["id"], image, body))

    print(f"  {matched} products get a photograph, {described} a real description")
    print(f"  {len(products) - matched} still without one")

    parts = [rows[i:i + CHUNK] for i in range(0, len(rows), CHUNK)]
    out = [HEADER]
    for part in parts:
        values = ",\n".join(
            f"    ({sql(pid)}, {sql(img)}, {sql(body)})" for pid, img, body in part
        )
        out.append(f"""
update public.products p
   set image_url = coalesce(v.image_url, p.image_url),
       description = coalesce(v.description, p.description),
       updated_at = now()
  from (values
{values}
  ) as v(id, image_url, description)
 where p.id = v.id;
""")
    out.append("""
select count(*) filter (where image_url is not null) as with_photo,
       count(*) filter (where image_url is null) as without_photo
  from public.products
 where is_active;
""")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("wrote", os.path.relpath(OUT, REPO), f"({len(parts)} statements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
