"""
Put the catalogue back in stock, and stop the trigger undoing it.

    python scripts/generate-stock.py

Writes supabase/schema-19-stock.sql.

THE PROBLEM
-----------
Every imported product reads "out of stock" on the site. Nothing is
actually out of stock: the spreadsheet says 3,393 of 3,405 are available
and the storefront feed agrees. schema-16 wrote that availability into
stock_status correctly -- and schema-07's trigger immediately overwrote
it, because that trigger derives the status from stock_quantity alone,
and the import had no counts to write.

THE FIX
-------
A merchant reselling 3,405 SKUs does not keep a count of each one, and
inventing 3,405 numbers to satisfy a trigger would be inventing data
that then drifts. So products say whether they are counted:

    track_stock = true    status follows the count, as now
    track_stock = false   status is whatever it is set to

Imported products are untracked and take their real availability from
the source. Anything counted in the warehouse can be switched to tracked
in admin, one product or a hundred at a time, and behaves exactly as
before.
"""

import collections
import importlib.util
import io
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEED = os.path.join(REPO, "images", "zion-products-feed.json")
OUT = os.path.join(REPO, "supabase", "schema-19-stock.sql")


def sql(value: str) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    feed = json.load(io.open(FEED, encoding="utf-8"))
    available = {}
    for product in feed:
        variants = product.get("variants") or []
        available[product["handle"]] = any(v.get("available") for v in variants)

    spec = importlib.util.spec_from_file_location(
        "build_catalogue", os.path.join(REPO, "scripts", "build-catalogue.py"))
    build = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(build)

    stdout, sys.stdout = sys.stdout, io.StringIO()
    try:
        products = build.main()
    finally:
        sys.stdout = stdout

    tally = collections.Counter()
    out_of_stock = []
    for product in products:
        # A product the feed no longer lists is left available rather than
        # hidden: absence from one fetch is not evidence it is gone.
        if available.get(product["handle"], True):
            tally["in-stock"] += 1
        else:
            tally["out-of-stock"] += 1
            out_of_stock.append(product["id"])

    print(f"catalogue       {len(products)}")
    print(f"  in stock      {tally['in-stock']}")
    print(f"  out of stock  {tally['out-of-stock']}")

    ids = ",\n    ".join(sql(i) for i in sorted(out_of_stock))

    body = f"""-- ===========================================================================
-- 19 — Stock that reflects reality
--
-- Generated by scripts/generate-stock.py. Do not hand-edit; re-run it.
--
-- Run AFTER schema-16. Safe to re-run.
--
-- WHY
-- Every imported product reads "out of stock" and none of them is. The
-- source says {tally['in-stock']} of {len(products)} are available; schema-16 wrote that
-- into stock_status, and schema-07's trigger overwrote it on the way in,
-- because it derives the status from stock_quantity and the import had
-- no counts to give it.
--
-- Inventing {len(products)} counts to satisfy the trigger would be inventing data,
-- and it would drift the first time anything sold. Instead a product now
-- says whether it is counted at all.
-- ===========================================================================

-- Counted in the warehouse, or simply stocked? Existing products keep
-- today's behaviour; the import does not.
alter table public.products
  add column if not exists track_stock boolean not null default true;

comment on column public.products.track_stock is
  'True: stock_status follows stock_quantity. False: stock_status is set directly.';

-- The trigger stops speaking for products nobody counts.
create or replace function public.derive_stock_status()
returns trigger
language plpgsql
as $$
begin
  if not new.track_stock then
    -- Untracked: whoever set the status meant it. Only an unrecognised
    -- value gets a default, so an insert that says nothing is stocked.
    if new.stock_status is null
       or new.stock_status not in ('in-stock', 'low-stock', 'out-of-stock') then
      new.stock_status := 'in-stock';
    end if;
    return new;
  end if;

  new.stock_status := case
    when new.stock_quantity <= 0 then 'out-of-stock'
    when new.stock_quantity <= new.low_stock_threshold then 'low-stock'
    else 'in-stock'
  end;
  return new;
end;
$$;

-- The imported catalogue is not counted.
update public.products
   set track_stock = false,
       stock_status = 'in-stock',
       updated_at = now()
 where id like 'zn-%';

-- Except the ones the source says are genuinely unavailable.
update public.products
   set stock_status = 'out-of-stock',
       updated_at = now()
 where id in (
    {ids}
 );

-- What happened, so the run can be checked rather than assumed.
select
  count(*) filter (where stock_status = 'in-stock') as in_stock,
  count(*) filter (where stock_status = 'low-stock') as low_stock,
  count(*) filter (where stock_status = 'out-of-stock') as out_of_stock,
  count(*) filter (where not track_stock) as untracked
  from public.products
 where is_active;
"""

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)
    print("\n  wrote", os.path.relpath(OUT, REPO))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
